### ISSUE TITLE
Setting up dotnet35 error 67 during install

### ISSUE THREAD

**Issue by crlink271986** [Mantas-2155X/illusion-wine-guide#11]
so following your guide "setup your wineprefix" part i get this error running winetricks -q dotnet35 install errror 67
everything else installs fine dxvk ole32 even dotnet472

**Comment by crlink271986** [comment]
forgot to mention  version is staging-7.17 on arch linux winetricks was updated via the wikipost on winehq not what was on pacman

**Comment by crlink271986** [comment]
may have found the solution you net to install both dotnet2.0 and sp1 (x64) before trying to install dotnet35

**Comment by crlink271986** [comment]
may have fixed it (wine error) it was reported on bugzilla a while back in 4.x got fixed in 5.x and appeared again in latest

solution
under winecfg go to libraries dll overrides add the new entry "ngen.exe" (wouthout quotes) and change the entry from wine (builtin) to Windows (native) then try to reinstall winetricks -q dotnet35sp1(am gonna test now and will close this issue if resolved

**Comment by Mantas-2155X** [comment]
While I have not encountered this issue myself, it should be useful for those who do. I have added a link to this issue in the setup-wineprefix part.
Thank you
