### ISSUE TITLE
[Test] Retest Mac OSX-12 (intel)

### ISSUE THREAD

**Issue by crlink271986** [Mantas-2155X/illusion-wine-guide#12]
just wanted to point out your guide is a little dated now the fact that dxvk isn't on mac os is false now if you use the unofficial wineskin server (by Gcenx on github) and update your winetricks on your .app your creating it's under dll--->dxvk(xxxx)-macos (latest as of writing is v 1103) If you don't test it i will myself and report back hopefully this will make illusion games run on macOS more smoothly

**Comment by Mantas-2155X** [comment]
Hello, I don't own any Mac devices, so if you are able to test and report back with results, that would be great :)

**Comment by Mantas-2155X** [comment]
Changed the dxvk notices in case there are mac users who have a working dxvk installation
