### ISSUE TITLE
Fullscreen may crash No Responding when return from File Dialog in Koikatsu

### ISSUE THREAD

**Issue by lasagnasu** [Mantas-2155X/illusion-wine-guide#13]
### Reproduce
1. enable full screen
2. open a file dialog in game, for example, the overlays
3. close the file dialog
4. the game don‘t respond

### Rejection
1. disable full screen
2. it will work fine
### issues
I'm not sure if other player or other illusion game have this issue. And if anyone comes to the same problem, I hope this will be helpful.

**Comment by Mantas-2155X** [comment]
Thank you, I've added it in the notes
