### ISSUE TITLE
Issues with HF Patch for AI Shoujo installer after installing dotnet

### ISSUE THREAD

**Issue by papaj-na-wrotkach** [Mantas-2155X/illusion-wine-guide#14]
I have a problem after installing `dotnet` as mentioned in `setup-wineprefix.md`:
https://github.com/Mantas-2155X/illusion-wine-guide/blob/183f0b9b5c89730964b665d0ab2d8f700de7b6fa/parts/setup-wineprefix.md?plain=1#L7-L8

I have described everything here: ManlyMarco/AI-HF_Patch#22

Any ideas what should I do to make the installer work with `dotnet35` and `dotnet472`?

**Comment by Mantas-2155X** [comment]
Added a notice that installing dotnet might prevent HF patch from installing. Closing as there isn't anything else I can do to resolve it
