### ISSUE TITLE
Issues with HF Patch for AI Shoujo installer  "This patch is inside of the game directory"

### ISSUE THREAD

**Issue by Makitova** [Mantas-2155X/illusion-wine-guide#17]
I followed all the guides but I can't find any folder like "D:\HFP" on my PC can you help me plz?
where should I past the AI Shoujo game files?

**Comment by Mantas-2155X** [comment]
I am not sure what you are asking for here
You want to install HF patch? In that case, run the installer in the same wineprefix as the game and you should be able to point it to the correct directory.

**Comment by Mantas-2155X** [comment]
closed due to inactivity
