### ISSUE TITLE
Help with SB3UtilityGUI

### ISSUE THREAD

**Issue by videoman614** [Mantas-2155X/illusion-wine-guide#18]
I followed the guide, selecting the necessary dependencies to install using both Lutris and Bottles, BetterRepack Koikatsu Sunshine runs without issues however I wasn't able to get SB3UtilityGUI to work.

I'm unable to see anything in the rendered view with this error ```E_NOTIMPL: The function called is not supported at this time (-2147467263)``` in the log output.

![Screenshot_20231114_222227](https://github.com/Mantas-2155X/illusion-wine-guide/assets/148925706/ba616486-a670-48db-9b1d-0ea6d04b69f4)

I can load the animation file but I'm unable to play and export it.

I'm not sure what dependency I'm missing.

**Comment by Mantas-2155X** [comment]
Hello, does the issue still happen if you run sb3 with `WINEDLLOVERRIDES="d3d11,dxgi=b"` env var?

**Comment by videoman614** [comment]
It's getting there but still broken.

After installing vcredist2010 and 2015, dotnet45 and 40 and adding the dll override for d3d11 and dxgi, the rendered view displays something however exporting is broken, the output file doesn't contain anything usable.

Looks like this now.
![Screenshot_20231115_120209](https://github.com/Mantas-2155X/illusion-wine-guide/assets/148925706/808e71e2-1ae7-4d1b-9edc-97a65dc72334)

Not sure if you want to see what's wrong with the exported animations so I'll attach them as well.

[00.zip](https://github.com/Mantas-2155X/illusion-wine-guide/files/13358825/00.zip)

**Comment by videoman614** [comment]
I'm an idiot, SB3UtilityGUI doesn't support KKS just KK which was why it wasn't exporting correctly.
