### ISSUE TITLE
Crash on title screen [fix included]

### ISSUE THREAD

**Issue by jmfergeau** [Mantas-2155X/illusion-wine-guide#4]
Hi. I just tried your method for koikatsu (betterrepack). But while it somewhat works with the default wine prefix, (it launches but without mods) it now just refuses totally to start. The Illusion splash screen appears, the girl says "illusion", then the window closes. The console drops this in the logs:

```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  10 (X_UnmapWindow)
  Resource id in failed request:  0x5400001
  Serial number of failed request:  540
  Current serial number in output stream:  541
wine: Unhandled page fault on read access to 0000000000000010 at address 00007FE4F3674424 (thread 0174), starting debugger...
```

In very rare cases, the window disappears but there's no error and koikatu.exe is still on. I can hear the music of the title screen but no window at all. Only way to quit it is to kill it in task manager.

Arch linux x64 with kernel 5.14.14-arch1-1, wine 6.18. Betterrepack RX7 updated with HF patch 3.12. no errors while following the instructions.

I could fix it by putting all the installed dlls to `native, integrated` instead of just `native`. Maybe you should add this detail in your guide ;)

**Comment by Mantas-2155X** [comment]
while I am not able to reproduce or test this, I have added it as a note in the guide
