### ISSUE TITLE
Add page on getting plugins to work

### ISSUE THREAD

**Issue by endless-devourer** [Mantas-2155X/illusion-wine-guide#9]
Is it possible to have a page that explains how to get certain launchers to work? Some games have custom launchers (such as ScrewThisNoise). Loading the launcher is fine, and I can run the game through the launcher. The issue is that the translation plugin doesn't work. Clicking on the language icon brings up the windows program error message (the one that says a serious problem had been encountered and the program needs to be closes) .

I'm guessing that there's still some compatibility issues but I'm not sure what they could be

edit:
Specifically, I can't seem to get the translation plugin to work. Don't know if it's a BepInEx issue or a wine issue

**Comment by Mantas-2155X** [comment]
Hello, if you follow the guide properly, both the launchers and plugins (including translation) should work correctly.
This definitely sounds like a wine configuration issue or a conflict with some other package (that could prevent BepInEx from working)

For BepInEx to work, you need to set `winhttp.dll` to `native,builtin` in winecfg.
That is done in the [setup-wineprefix](https://github.com/Mantas-2155X/illusion-wine-guide/blob/master/parts/setup-wineprefix.md) part of the guide. Specifically, the `Allow the native winhttp wrapper be loaded` section.

Also, please make sure that you don't have `plugins` and `Plugins` in the BepInEx directory. In that case just merge them and try again.

**Comment by endless-devourer** [comment]
My bad, definitely user error on my part. I messed up on the winhttp bit (should've just copied and pasted). Thanks, closing issue
